{
    "name":"root",
    "priority":"1",
    "health":"1",
    "children":[
        {
            "name":"ex1",
            "priority":"0.2",
            "health":"0.2",
            "children":[
                {
                    "name":"ex1.1",
                    "priority":"0.4",
                    "health":"0.3",
                    "children":[]
                },
                {
                    "name":"ex1.2",
                    "priority":"0.6",
                    "health":"0.3",
                    "children":[]
                }
            ]
        },
        {
            "name":"ex2",
            "priority":"0.3",
            "health":"0.3",
            "children":[]
        },
        {
            "name":"Example 003",
            "priority":"0.5",
            "health":"0.3",
            "children":[]
        }
    ]
}
